{% set name = "aiidalab-widgets-base" %}
{% set version = "2.3.0a3" %}
{% set python_min = "3.9" %}
{% set sha256 = "35ba7594a0aedb723b5f099ae40760196795da8af87fb3583942c7d470fcbcd9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiidalab_widgets_base-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  # We can only support linux because of 'povray' dependency
  # https://github.com/conda-forge/povray-feedstock/blob/a0b75ca48b7767ba4f5b4bb0c5ff2d4a15b85f71/recipe/meta.yaml#L14
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pycifrw >=4.4,<5.dev0
    - aiida-core >=2.1,<3
    - aiidalab >=21.11.2
    - ansi2html >=1.6,<2.dev0
    - ase >=3.18,<4.dev0,<3.23
    - bokeh >=2.0,<3.dev0
    - humanfriendly >=10.0,<11.dev0
    - ipytree >=0.2,<1.dev0
    - traitlets >=5.4,<6.dev0
    - ipywidgets >=7.7,<8.dev0
    - widgetsnbextension <3.6.3
    - pymysql >=0.9,<1.dev0
    - nglview >=3.0,<4.dev0
    - spglib >=1.14,<3
    - vapory >=0.1.2,<0.2.dev0
    - pandas >=2.1,<3.dev0

test:
  imports:
    - aiidalab_widgets_base
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aiidalab/aiidalab-widgets-base
  summary: Reusable widgets for AiiDAlab applications.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - unkcpz
    - danielhollas
    - yakutovicha
